/**
 * CNS Manager Setup Wizard
 *
 * Copies the bundled cns-server.js into the WinCC OA project, generates
 * a security token, writes the .env config, registers the manager in
 * config/progs, and auto-configures VS Code settings so the extension
 * connects immediately.
 */

import * as vscode from 'vscode';
import * as fs from 'fs/promises';
import * as path from 'path';
import * as crypto from 'crypto';
import { log } from './extensionOutput.js';
import { managerExists, addManager, getNextFreeManagerNumber } from './managerConfigHelper.js';

const CNS_SUBPATH = 'javascript/vscodeCns';
const CNS_SCRIPT_NAME = 'index.js';
const DEFAULT_PORT = 4712;

export class CnsSetupWizard {
  /**
   * Check whether the CNS manager is already registered in config/progs.
   */
  static async isCnsManagerInstalled(projectDir: string): Promise<boolean> {
    return managerExists(projectDir, 'node', 'vscodeCns');
  }

  /**
   * Run the full setup: copy script, generate token, write .env,
   * register manager, and auto-configure VS Code settings.
   *
   * @returns true if setup completed successfully
   */
  static async runSetup(
    projectDir: string,
    projectName: string,
    extensionPath: string,
  ): Promise<boolean> {
    log(`Starting CNS manager setup for project: ${projectName}`);

    const answer = await vscode.window.showInformationMessage(
      `CNS manager not found in project "${projectName}". Install now?`,
      { modal: true },
      'Install',
      'Skip',
    );

    if (answer !== 'Install') {
      log('CNS setup cancelled by user');
      return false;
    }

    const token = crypto.randomBytes(32).toString('hex');

    try {
      await vscode.window.withProgress(
        {
          location: vscode.ProgressLocation.Notification,
          title: `Installing CNS manager for ${projectName}`,
          cancellable: false,
        },
        async progress => {
          // Step 1 — Copy cns-server.js into the project
          progress.report({ increment: 0, message: 'Copying CNS server script…' });
          await this.copyServerScript(extensionPath, projectDir);

          // Step 2 — Write .env
          progress.report({ increment: 40, message: 'Creating configuration…' });
          await this.createEnvFile(projectDir, token);

          // Step 3 — Register manager in config/progs
          progress.report({ increment: 60, message: 'Adding manager to project…' });
          await this.registerManager(projectDir);

          // Step 4 — Auto-configure VS Code settings
          progress.report({ increment: 80, message: 'Configuring VS Code settings…' });
          await this.configureSettings(token);

          progress.report({ increment: 100, message: 'Done!' });
        },
      );

      const restart = await vscode.window.showInformationMessage(
        'CNS manager installed successfully! Restart the WinCC OA project for the manager to start.',
        'OK',
      );

      log('CNS manager setup completed successfully');
      return true;
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      log(`CNS setup failed: ${msg}`);
      vscode.window.showErrorMessage(`CNS manager installation failed: ${msg}`);
      return false;
    }
  }

  // ── private helpers ──────────────────────────────────────────────

  private static async copyServerScript(extensionPath: string, projectDir: string): Promise<void> {
    const src = path.join(extensionPath, 'managers', 'cns-server.js');
    const destDir = path.join(projectDir, CNS_SUBPATH);
    const dest = path.join(destDir, CNS_SCRIPT_NAME);

    await fs.mkdir(destDir, { recursive: true });
    await fs.copyFile(src, dest);
    log(`Copied CNS server script to ${dest}`);
  }

  private static async createEnvFile(projectDir: string, token: string): Promise<void> {
    const envPath = path.join(projectDir, CNS_SUBPATH, '.env');
    const content = [
      '# WinCC OA CNS Server Configuration',
      '# Auto-generated by WinCC OA CNS Browser extension',
      '',
      `CNS_SERVER_TOKEN=${token}`,
      `CNS_SERVER_PORT=${DEFAULT_PORT}`,
      '',
    ].join('\n');

    await fs.writeFile(envPath, content, 'utf8');
    log(`Created .env at ${envPath}`);
  }

  private static async registerManager(projectDir: string): Promise<void> {
    const already = await managerExists(projectDir, 'node', 'vscodeCns');
    if (already) {
      log('CNS manager already registered in config/progs — skipping');
      return;
    }

    await addManager(projectDir, {
      component: 'node',
      startMode: 'always',
      secKill: 30,
      restartCount: 3,
      resetMin: 1,
      options: 'vscodeCns\\index.js',
    });
  }

  private static async configureSettings(token: string): Promise<void> {
    const cfg = vscode.workspace.getConfiguration('winccoaCns');
    await cfg.update('serverUrl', `http://localhost:${DEFAULT_PORT}`, vscode.ConfigurationTarget.Workspace);
    await cfg.update('token', token, vscode.ConfigurationTarget.Workspace);
    log('Auto-configured winccoaCns.serverUrl and winccoaCns.token');
  }
}
